'use client';

import React from 'react';

type Props = {
  mode: 'driving' | 'walking';
  playing: boolean;
  progress: number;
  originLabel: string;
  schoolName: string;
  distanceKm: number | null;
  durationMin: number | null;
};

export default function SchoolRunScene({ mode, playing, progress, originLabel, schoolName, distanceKm, durationMin }: Props) {
  const p = Math.max(0, Math.min(1, Number.isFinite(progress) ? progress : 0));
  const x = 12 + p * 76;
  return (
    <section className="run-scene" aria-label={`School run from ${originLabel} to ${schoolName}`}>
      <div className="run-head">
        <div><div className="run-kicker">A little school-run story</div><h3>{mode === 'walking' ? 'The parents walk it together.' : 'The family heads out together.'}</h3><p>{mode === 'walking' ? 'Short routes stay on foot.' : 'Longer routes switch to the family car.'} The map remains the source of truth for the real route.</p></div>
        <div className="run-pills"><span>{distanceKm == null ? 'Route pending' : `${distanceKm.toFixed(1)} km`}</span><span>{durationMin == null ? '—' : `~${durationMin} min`}</span><span>{Math.round(p * 100)}% complete</span></div>
      </div>
      <div className="run-stage">
        <div className="sun"/><div className="cloud c1"/><div className="cloud c2"/><div className="tree t1"/><div className="tree t2"/>
        <div className="home"><div className="tower"><i/><i/><i/></div><div className="small-home"><i/><i/></div><label>{originLabel}</label></div>
        <div className="school"><div className="roof"/><div className="school-box"><i/><i/><i/><b/></div><label>{schoolName}</label></div>
        <div className="road"><div/><div className="two"/></div>
        <div className="traveller" style={{left:`${x}%`}}>
          {mode === 'walking' ? <div className={`couple ${playing ? 'moving' : ''}`}>
            {[0,1].map(i=><div key={i} className={`person ${i ? 'b' : 'a'}`}><span className="head"/><span className="body"/><span className="arm l"/><span className="arm r"/><span className="leg l"/><span className="leg r"/></div>)}<span className="heart">♥</span>
          </div> : <div className={`car ${playing ? 'moving' : ''}`}><div className="shadow"/><div className="car-body"/><div className="cabin"><span/><span/></div><div className="wheel w1"/><div className="wheel w2"/><i className="driver"/><i className="passenger"/><b>FAMILY</b></div>}
        </div>
        <div className="start"/><div className="pin">S</div>
        <div className="progress"><div><span style={{width:`${p * 100}%`}}/></div><small><b>Society</b><b>{playing ? (mode === 'walking' ? 'Walking together' : 'Driving together') : 'Paused'}</b><b>School</b></small></div>
      </div>
      <style jsx>{`
        .run-scene{border-top:1px solid var(--color-border);background:linear-gradient(180deg,#fffdf9,#f5f0e8)}
        .run-head{padding:17px 18px 14px;display:flex;align-items:flex-end;justify-content:space-between;gap:14px}.run-kicker{font-size:10px;font-weight:900;letter-spacing:.14em;text-transform:uppercase;color:var(--color-primary)}.run-head h3{margin:4px 0 0;font-size:17px;font-weight:900;color:var(--color-content)}.run-head p{margin:6px 0 0;max-width:680px;font-size:11px;line-height:1.45;color:var(--color-content-muted)}.run-pills{display:flex;flex-wrap:wrap;justify-content:flex-end;gap:6px}.run-pills span{padding:7px 9px;border:1px solid var(--color-border);border-radius:999px;background:#fff;font-size:9px;font-weight:800}
        .run-stage{position:relative;height:255px;overflow:hidden;background:linear-gradient(180deg,#dff0f5 0%,#edf4ea 57%,#deead2 100%)}.sun{position:absolute;width:150px;height:150px;top:-60px;right:12%;border-radius:50%;background:radial-gradient(circle,rgba(255,239,185,.9),transparent 70%)}.cloud{position:absolute;width:105px;height:26px;border-radius:999px;background:rgba(255,255,255,.7)}.cloud:before,.cloud:after{content:'';position:absolute;bottom:5px;border-radius:50%;background:rgba(255,255,255,.75)}.cloud:before{width:34px;height:34px;left:18px}.cloud:after{width:40px;height:40px;right:13px;bottom:2px}.c1{left:8%;top:30px}.c2{right:25%;top:55px;transform:scale(.7)}
        .road{position:absolute;left:6%;right:6%;bottom:43px;height:78px;border-radius:22px 22px 0 0;transform:perspective(340px) rotateX(42deg);transform-origin:bottom;background:linear-gradient(90deg,#aab2b6,#89959b,#aab2b6);box-shadow:0 -14px 28px rgba(55,74,67,.12)}.road>div{position:absolute;left:4%;top:36px;width:92%;height:4px;border-radius:999px;background:repeating-linear-gradient(90deg,#fff6bc 0 30px,transparent 30px 52px)}.road .two{top:51px;opacity:.22}
        .home,.school{position:absolute;bottom:67px;z-index:3;display:flex;flex-direction:column;align-items:center;gap:5px}.home{left:3%}.school{right:3%}.home label,.school label{max-width:135px;padding:4px 7px;border-radius:999px;background:#fffffff0;box-shadow:0 4px 12px #2536301f;color:#334044;font-size:8px;font-weight:900;text-align:center}.tower{position:relative;width:69px;height:70px;padding:7px 6px;border:2px solid #7d8e96;display:flex;justify-content:space-around;background:linear-gradient(#f2eee5,#d2d1c9);box-shadow:0 7px 13px #2b404526}.tower i,.small-home i{width:11px;height:14px;background:#83a8b7;border-radius:2px;box-shadow:0 9px 0 #83a8b7,0 18px 0 #83a8b7}.small-home{position:absolute;width:46px;height:46px;left:-27px;bottom:15px;padding:5px;display:flex;justify-content:space-around;border:2px solid #89969a;background:#ddd9d0}.small-home i{width:9px;height:10px;box-shadow:0 8px 0 #83a8b7,0 16px 0 #83a8b7}.roof{width:102px;height:20px;margin-bottom:-5px;border-radius:4px;background:linear-gradient(135deg,#cf603d,#963d2c);transform:perspective(160px) rotateX(28deg)}.school-box{position:relative;width:88px;height:65px;border:2px solid #a36a53;background:linear-gradient(#ffe8d4,#f0c6a7);box-shadow:0 8px 15px #5235262e}.school-box b{position:absolute;left:34px;bottom:0;width:19px;height:30px;border-radius:7px 7px 0 0;background:#855542}.school-box i{position:absolute;top:13px;width:14px;height:14px;border:2px solid #f8d19d;background:#7da6bb}.school-box i:nth-child(1){left:9px}.school-box i:nth-child(2){left:35px}.school-box i:nth-child(3){right:9px}
        .tree{position:absolute;bottom:64px;width:11px;height:37px;z-index:1;border-radius:4px;background:#7c5a45}.tree:before{content:'';position:absolute;width:43px;height:43px;left:-16px;top:-26px;border-radius:50%;background:#5f8b6d;box-shadow:9px 4px 0 #4268512e}.t1{left:18%}.t2{right:18%;transform:scale(.78)}
        .traveller{position:absolute;bottom:88px;z-index:8;transform:translateX(-50%);transition:left .22s ease-out;filter:drop-shadow(0 7px 6px #20332d33)}.couple{position:relative;width:68px;height:73px}.person{position:absolute;bottom:0;width:23px;height:62px}.person.a{left:5px}.person.b{left:37px;transform:scale(.95)}.person .head,.car i{position:absolute;border-radius:50%;background:#e8b38d;border:1px solid #3c281f2e}.person .head{width:16px;height:16px;top:0;left:3px}.person .body{position:absolute;top:17px;left:1px;width:21px;height:26px;border-radius:9px 9px 6px 6px;background:#315d84}.person.b .body{background:#d2745c}.person .arm,.person .leg{position:absolute;width:5px;border-radius:999px;background:#30434a;transform-origin:50% 6%}.person .arm{top:20px;height:23px}.person .leg{top:40px;height:25px}.person .arm.l{left:0;transform:rotate(24deg)}.person .arm.r{right:0;transform:rotate(-24deg)}.person .leg.l{left:5px;transform:rotate(15deg)}.person .leg.r{right:4px;transform:rotate(-14deg)}.couple.moving .leg.l{animation:legA .4s ease-in-out infinite alternate}.couple.moving .leg.r{animation:legB .4s ease-in-out infinite alternate}.couple.moving .arm.l{animation:armA .4s ease-in-out infinite alternate}.couple.moving .arm.r{animation:armB .4s ease-in-out infinite alternate}.heart{position:absolute;left:27px;top:0;color:#df6a63;font-size:12px;animation:heart 1.1s ease-in-out infinite}
        .car{position:relative;width:106px;height:63px}.shadow{position:absolute;left:8px;bottom:0;width:90px;height:12px;border-radius:50%;background:#1f342d45;filter:blur(4px)}.car-body{position:absolute;left:4px;bottom:9px;width:98px;height:28px;border-radius:17px 19px 8px 8px;border:2px solid #8c969c;background:linear-gradient(#fff,#d8dde0)}.cabin{position:absolute;left:28px;bottom:31px;width:51px;height:27px;border:2px solid #7b8991;border-radius:14px 16px 5px 5px;background:linear-gradient(#dbe7ed,#a8bcc6);transform:skewX(-8deg)}.cabin span{position:absolute;top:5px;width:19px;height:12px;border-radius:4px;background:#466274}.cabin span:first-child{left:4px}.cabin span:last-child{right:4px}.wheel{position:absolute;bottom:2px;width:18px;height:18px;border-radius:50%;background:#20262a;border:4px solid #6d7579}.w1{left:16px}.w2{right:16px}.car.moving .wheel{animation:spin .5s linear infinite}.car i{z-index:3;top:28px;width:11px;height:11px}.car .driver{left:36px}.car .passenger{left:64px}.car b{position:absolute;right:-5px;top:-3px;padding:2px 5px;border-radius:999px;border:1px solid #aab4b8;background:#fff;color:#6d777c;font-size:6px;letter-spacing:.08em}
        .start{position:absolute;left:10.7%;bottom:93px;z-index:7;width:12px;height:12px;border-radius:50%;background:#0f4c81;border:3px solid white}.pin{position:absolute;right:8.8%;bottom:87px;z-index:7;width:27px;height:27px;display:grid;place-items:center;border-radius:50% 50% 50% 0;transform:rotate(-45deg);background:var(--color-accent);color:white;border:3px solid white;font-size:10px;font-weight:900}
        .progress{position:absolute;left:10%;right:10%;bottom:10px;z-index:10}.progress>div{height:6px;overflow:hidden;border-radius:999px;background:#ffffff99;border:1px solid #5b736929}.progress>div span{display:block;height:100%;border-radius:inherit;background:linear-gradient(90deg,#0f4c81,#3f8f80,#e9845e);transition:width .2s}.progress small{margin-top:5px;display:flex;justify-content:space-between;color:#4c5b58;font-size:8px;font-weight:800;text-transform:uppercase;letter-spacing:.08em}
        @keyframes legA{from{transform:rotate(22deg)}to{transform:rotate(-22deg)}}@keyframes legB{from{transform:rotate(-22deg)}to{transform:rotate(22deg)}}@keyframes armA{from{transform:rotate(-25deg)}to{transform:rotate(25deg)}}@keyframes armB{from{transform:rotate(25deg)}to{transform:rotate(-25deg)}}@keyframes spin{to{transform:rotate(360deg)}}@keyframes heart{0%,100%{transform:scale(.9);opacity:.65}50%{transform:scale(1.18);opacity:1}}
        @media(max-width:720px){.run-head{align-items:flex-start;flex-direction:column}.run-pills{justify-content:flex-start}.run-stage{height:228px}.home{left:1%}.school{right:1%}.home label,.school label{max-width:105px}.road{left:3%;right:3%}.run-head h3{font-size:15px}.run-head p{font-size:10px}}
        @media(prefers-reduced-motion:reduce){.couple.moving .leg.l,.couple.moving .leg.r,.couple.moving .arm.l,.couple.moving .arm.r,.heart,.car.moving .wheel{animation:none!important}}
      `}</style>
    </section>
  );
}
